# Configure notifications in Azure DevOps
trigger: none

pr: none

stages:
- stage: Run

  variables:
  - template: ./templates/variables/globals.yml

  jobs:
  - job: Run
    timeoutInMinutes: 120

    pool:
      name: azsdk-pool-mms-ubuntu-2204-general
      vmImage: ubuntu-22.04

    variables:
      Organization: azure-sdk
      Project: internal
      DotNetDevOpsFeed: "https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json"

    steps:
      - task: AzureCLI@2
        displayName: 'Run Team/Notification Creator'
        inputs:
          azureSubscription: 'opensource-api-connection'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            Write-Host 'az account get-access-token --scope '66b6ea26-954d-4b68-8f48-71e3faec7ad1/.default' --query accessToken --output tsv'
            $token = az account get-access-token --scope '66b6ea26-954d-4b68-8f48-71e3faec7ad1/.default' --query accessToken --output tsv
            Write-Host "##vso[task.setvariable variable=__throwawaysecret;issecret=true]$token"
            $headers = @{ Authorization="Bearer $token"; "api-version"="2019-10-01" }
            Write-Host 'invoke-restmethod -Headers $headers -Method GET -Uri https://repos.opensource.microsoft.com/api/people/links'
            Invoke-RestMethod -Headers $headers -Method GET -Uri https://repos.opensource.microsoft.com/api/people/links
